name: ScottMosesMurray
favicon: null
layout_spectrum: 0.14334616507403553
typography_spectrum: 0.3551022878382355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5498431748710573
  lightness: 0.23771319864317775
  saturation: 0.671283709583804
  rhythmicContrast: 0.3640256985090673
purpose: []
