name: ScottMosesMurray
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040504'
    - '#767e02'
    - '#1acbb3'
    - '#dbf915'
  brandStrength: 0
  lightness: 0.23771319864317775
  saturation: 0.671283709583804
  rhythmicContrast: 0.25
purpose: []
